test(eth-proofs): Fix and test Eth proofs on NEAR
near/rainbow-bridge pull request #550
Opened 2021-04-07 12:43 UTC by mfornet

The logic for proof verification currently has some drawbacks.
The logic to verifacate proofs from the Ethereum blockchain
in the NEAR side of the bridge was improved with:

Handle all types of keys, previously it was only possible to
prove receipts and transactions, now also state can be proved.

It doesn't use unrecoverable erros anymore to mark an invalid
proof, instead it always return boolean value.

Some nits in the code.

The main resources used to understand and implement the verification was:

https://eth.wiki/en/fundamentals/patricia-tree
https://eth.wiki/fundamentals/rlp

Test plan
=========

Verify all recipts and transaction from the Ethereum blockchain up to some point can be validated.
Verify state/storage proofs can be validated with real data extracted from Ethereum.
verify_trie_proof code has 100% coverage.

2021-04-11 17:32 UTC, abacabadabacaba requested changes
Here are some suggested changes. These are not enough, there are still cases where this code will panic on invalid proofs. It will also not accept proofs with values shorter than 32 bytes (and can accept invalid proofs for trees that include such values). There is still a lot of work to do with fixing this code.

2021-04-11 17:32 UTC, abacabadabacaba commented on contracts/near/eth-prover/src/lib.rs
> +            if dec.as_raw() != (expected_root.0).0 {
This won't work because `expected_root` is `H256` so its length must be 32.

2021-04-11 17:32 UTC, abacabadabacaba commented on contracts/near/eth-prover/src/lib.rs
> +                    .unwrap_or_default()
```suggestion
                dec.at(16).unwrap().as_val::<Vec<u8>>() == Ok(expected_value)
```

2021-04-11 17:32 UTC, abacabadabacaba commented on contracts/near/eth-prover/src/lib.rs
>              } else if key_index < key.len() {
We can probably assume that `key_index <= key.len()`, so this check is not necessary.

2021-04-11 17:32 UTC, abacabadabacaba commented on contracts/near/eth-prover/src/lib.rs
> +                    .and_then(|rlp| rlp.as_val::<Vec<u8>>());
```suggestion
                    .unwrap().
                    .as_val::<Vec<u8>>();
```

2021-04-11 17:32 UTC, abacabadabacaba commented on contracts/near/eth-prover/src/lib.rs
> +                        new_expected_root.unwrap().into(),
```suggestion
                new_expected_root.map(|root| Self::_verify_trie_proof(
                        root.into(),
                        [...]
                    ).unwrap_or_default()
```

2021-04-11 17:32 UTC, abacabadabacaba commented on contracts/near/eth-prover/src/lib.rs
> +                    && expected_value == current_value.unwrap()
```suggestion
                    && current_value == Ok(expected_value)
```

2021-04-11 17:32 UTC, abacabadabacaba commented on contracts/near/eth-prover/src/lib.rs
> +                    && key_end.to_vec() == &key[key_index..]
```suggestion
                    && key_end == &key[key_index..]
```

2021-04-11 17:32 UTC, abacabadabacaba commented on contracts/near/eth-prover/src/lib.rs
>                  let key_end = &nibbles[2..];
```suggestion
                let key_end = &nibbles[1..];
```

2021-04-11 17:32 UTC, abacabadabacaba commented on contracts/near/eth-prover/src/lib.rs
>                      && Self::concat_nibbles(key_end.to_vec()) == &key[key_index + 1..]
```suggestion
                    && key_end == &key[key_index..]
```

2021-04-11 17:32 UTC, abacabadabacaba commented on contracts/near/eth-prover/src/lib.rs
> +                    && expected_value == current_value.unwrap()
```suggestion
                    && current_value == Ok(expected_value)
```

2021-04-11 17:32 UTC, abacabadabacaba commented on contracts/near/eth-prover/src/lib.rs
> +                    && key_index <= key.len()
Redundant check.

2021-04-11 17:32 UTC, abacabadabacaba commented on contracts/near/eth-prover/src/lib.rs
> +                    && shared_nibbles.to_vec() == &key[key_index..key_index + extension_length]
No need to convert to a vector.

2021-04-11 17:32 UTC, abacabadabacaba commented on contracts/near/eth-prover/src/lib.rs
>                  let extension_length = 1 + shared_nibbles.len();
```suggestion
                let shared_nibbles = &nibbles[1..];
                let extension_length = shared_nibbles.len();
```

2021-04-11 17:32 UTC, abacabadabacaba commented on contracts/near/eth-prover/src/lib.rs
> +                    && shared_nibbles.to_vec() == &key[key_index + 1..key_index + extension_length]
```suggestion
                    && shared_nibbles == &key[key_index..key_index + extension_length]
```

2021-04-14 10:31 UTC, mfornet commented
Closing in favor of #556

2021-04-14 10:31 UTC, closed without merging